### ISSUE TITLE
Expression rejects all packages

### ISSUE THREAD

**Issue by tobsch** [andgineer/docker-amazon-dash-button-hack#1]
Hi there,

I'm thrilled to try this package. Unfortunately, I ended up with the following problem running it on Synology / Docker:

https://github.com/secdev/scapy/issues/722

Any ideas?
Many thanks,

Tobias

**Comment by andgineer** [comment]
We can use developer version of scapy as they recommend.

But on scapy site they say that python3 is not supported.
I am using python3 fork of this lib [scapy-python3](https://github.com/phaethon/scapy) ([pip.requirements.txt](https://github.com/masterandrey/docker-amazon-dash-button-hack/blob/master/pip.requirements.txt))

And it works fine for me.
May be you installed scapy instead?

**Comment by tobsch** [comment]
Nono, I just straight-on used the Dockerhub version of your image on my synology. I even copied your recommended settings.json file...

Maybe it's worth a try to switch to the dev version?

**Comment by andgineer** [comment]
How did you managed to make it work?

**Comment by tobsch** [comment]
I manipulated the "sniff(...)" call like this "sniff(iface='eth0'...)"

Any ideas how to integrate this in a nice way?

Tobias

**Comment by andgineer** [comment]
environment variable for doker?
So add to docker command line:
`docker run -e "SNIFF_IFACE=eth0" ...`
And in code 
```
    import os
    sniff(iface=os.environ.get('SNIFF_IFACE', None)...)
```

So by default scapy will use first interface and if you want you can use specific interface.

We definitely do not want to remove ARP filter (it would be poor performance).
And with filter scapy wants specific interface. 
I think there is no way for application to know which interface is the right one..

**Comment by andgineer** [comment]
https://github.com/secdev/scapy/issues/722 was closed
