### ISSUE TITLE
amazon

### ISSUE THREAD

**Issue by fun4stuff** [andgineer/docker-amazon-dash-button-hack#2]
confused about the following commands.

docker rm -f amazon_dash
docker run --net host -it --name amazon_dash -v $PWD/amazon-dash-private:/amazon-dash-private:ro masterandrey/amazon-dash

The name of the project is not amazon_dash....

**Comment by andgineer** [comment]
`docker run` command creates container with name amazon_dash (`--name option`).
So `docker rm` just make sure there are no such container and deletes it if it exists.
This way you can run this command lines many times

**Comment by andgineer** [comment]
Oh dear me :(
The docker hub container name is wrong. Fixed.

**Comment by fun4stuff** [comment]
Thanks, thought something was up. I'm still new to docker
