### ISSUE TITLE
settings.json is not found

### ISSUE THREAD

**Issue by snowe2010** [andgineer/docker-amazon-dash-button-hack#8]
Following all instructions, I receive this error, even though I have copied your `settings.json` exactly. There is no description of what should actually be _in_ the `settings.json`, so I don't know if that might be causing the issue. 

```
[~] # docker rm -f amazon_dash
amazon_dash
[~] # docker run --net host -it --name amazon_dash -v $PWD/amazon-dash-private:/amazon-dash-private:ro masterandrey/docker-amazon-dash-butto>

No amazon-dash-private/settings.json found.
If you run application in docker container you
should connect volume with setting files, like
    -v $PWD/amazon-dash-private:/amazon-dash-private:ro
[~] # ls
amazon-dash-private/  index_default.html
[~] # ls amazon-dash-private/
amazon-dash-hack.json  buttons.json  ifttt-key.json  settings.json
[~] #
```

**Comment by snowe2010** [comment]
I think it might be because `root` is not prepended to the path here? https://github.com/masterandrey/docker-amazon-dash-button-hack/blob/master/src/amazon_dash.py#L20

**Comment by andgineer** [comment]
https://github.com/masterandrey/docker-amazon-dash-button-hack/
...In folder amazone-dash-private you should have...

There are your secrets so you have to create all this files by youself

**Comment by snowe2010** [comment]
@masterandrey 	I don't understand what you are saying. I have those files in the appropriate folder. The amazon_dash.py script is telling me the file doesn't exist though, even though it does exist.

**Comment by snowe2010** [comment]
Why did you close the issue? I showed you the directory structure I have. `settings.json` is in the right folder.

**Comment by andgineer** [comment]
I am sorry!
At first I was was sure you do not have the files, so I fixed the readme to stress that you need the files and closed the bug.

Now I see the bug and my tests do not see it because they work from different folder.
I fixed it.

**Comment by snowe2010** [comment]
Fantastic. Thank you!
